image: node:16-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - test
  - lint
  - build
  - update-readme

install:
  stage: install
  script:
    - yarn
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

build:
  stage: build
  script:
    - yarn build

test:
  stage: test
  script:
    - yarn test

lint:
  stage: lint
  script:
    - yarn lint

update-readme:
  stage: update-readme
  script:
    - yarn make-badges
