stages:
  - install
  - test
  - lint
  - build
  - update-readme

install:
  stage: install
  image: node:16-alpine
  script:
    - yarn
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

build:
  stage: build
  image: node:16-alpine
  script:
    - yarn build

test:
  stage: test
  image: node:16-alpine
  script:
    - yarn test

lint:
  stage: lint
  image: node:16-alpine
  script:
    - yarn lint

update-readme:
  stage: update-readme
  image: node:16-alpine
  script:
    - make-badges
