stages:
  - install
  - test
  - build

install:
  stage: install
  image: node:16-alpine
  script:
    - yarn
  artifacts:
    when: always

build:
  stage: build
  image: node:16-alpine
  script:
    - yarn build

test:
  stage: test
  image: node:16-alpine
  script:
    - yarn test
