image: node:16-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - test_and_lint
  - build
  - deploy

install:
  stage: install
  script:
    - yarn
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

build:
  stage: build
  script:
    - yarn build

test:
  stage: test_and_lint
  script:
    - yarn test

lint:
  stage: test_and_lint
  script:
    - yarn lint

deploy:
  stage: deploy
  when: manual
  script:
    - echo "Deploying..."
    - sleep 9
    - echo "DEPLOY DONE HURRAY"
