name: UkeTabs CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    name: 'install'
    runs-on: ubuntu-latest
    steps:
      - run: yarn

  test_and_lint:
    name: 'test_and_lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: yarn test
      - run: yarn lint

  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: yarn build

  deploy:
    name: 'deploy'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
      - run: sleep 9
      - run: echo "DEPLOY DONE HURRAY"
    
